# PHP


phpfpm:
  restart: always
  build: php-fpm 
# user: "$(id -u gircueel)"
  user: "1000"
  volumes:
    - ./php-fpm/php-fpm.conf:/usr/local/etc/php-fpm.conf
    - ./php-fpm/php.ini:/usr/local/etc/php/php.ini
    - ./app:/var/www/html
    - ./log/php-fpm:/var/log/php-fpm
  links:
    - db:db

# NGINX
nginx:
  restart: always
  image: nginx:1.10
  volumes:
  ports:
    - "8000:80"
  links:
    - phpfpm:phpfpm
  volumes:
    - ./nginx/vhost.conf:/etc/nginx/conf.d/default.conf
    - ./app:/var/www/html
    - ./log/nginx:/var/log/nginx

# MYSQL
db:
  restart: always
  image: mysql:5.6
  ports:
    - "3306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: 123456
    MYSQL_USER: user
    MYSQL_PASSWORD: password
    MYSQL_DATABASE: database
  volumes:
    - ./mysql/databases:/var/lib/mysql
    - ./log/mysql:/var/log/mysql

#  - /var/run/mysqld/mysqld.sock:/var/run/mysqld/mysqld.sock
